Лабораторная работа 2
MargaritaLebedeva11/DD-PY2 pull request #2
Opened 2023-01-15 15:38 UTC by MargaritaLebedeva11

В задании по созданию класса Library не совсем уверена, можно ли было пользоваться pydantic, но в условии задания никаких ограничений на это не накладывалось.

2023-01-16 14:22 UTC, TimurIslamgulov requested changes
нет, вы должны опираться только на свои созданные классы

2023-01-16 17:51 UTC, MargaritaLebedeva11 commented
> нет, вы должны опираться только на свои созданные классы

А почему это никак не оговаривается в условии задания? Ничего про это в условии нет. Никак не оговорено то, что необходимо использовать уже созданный класс и что нельзя написать новый.

Почему Вы поставили за второе задание 0? Оно же выполнено и работает так, как требуется. Просто другим способом сделано. Это же не 0

2023-01-16 18:08 UTC, MargaritaLebedeva11 commented
> нет, вы должны опираться только на свои созданные классы

Задание исправлено

2023-01-17 13:42 UTC, TimurIslamgulov approved these changes
все ок, во втором задании логично бы сделать импорт первого задания

2023-01-25 21:58 UTC, merged